### ISSUE TITLE
frontend job manager

### ISSUE THREAD

**Issue by lauhin** [j-easy/easy-batch#192] opened 2016-06-04 12:01 UTC
Hi there,

Wouldn't it be great to have a frontend for managing easybatch jobs? A frontend where we can upload jars and manage them by starting, stopping, reschedule... the jobs? A bit like Apache Flink's concept.

Thx in advance!

Laurent

**Comment by benas** [comment] 2016-06-04 21:40
Hi Laurent,

Currently there is no admin UI for easy batch jobs. Since there is no `JobRepository` concept, it is impossible to save job definitions in a persistent store. But with the idea of uploading jobs as jar files, it would be possible to manage jobs through an admin UI without a `JobRepository`. I'll try to come up with a working POC and keep you informed.

Kind regards
Mahmoud

**Comment by benas** [comment] 2016-09-27 16:01
Hi Laurent,

I'm really struggling to find a clean way to implement this feature:

* The idea of uploading fat jars and launching them is a not bad. But the problem is that the admin interface should have the rights to launch java processes on the machine. This would be a dangerous decision in terms of security. Do you agree? More over, I already expect hear-pulling sessions to correctly handle class loaders between jobs jars..

* The other alternative is to run jobs **inside** the jvm running the admin interface. This is possible since Easy Batch jobs are `Callable` objects, we can use a [ManagedExecutorService](http://docs.oracle.com/javaee/7/api/javax/enterprise/concurrent/ManagedExecutorService.html) and launch them though the UI. But this is not good neither: I've never imagined running a batch job inside a servlet container..

The scope of the admin UI should be clearly defined. The user (job operator) should be able to:

* inspect running jobs
* start/stop jobs
* import new jobs

If we forget a little about Easy Batch , do you think this is feasible with `Callable` Java objects? 
There is no `JobInstance` and `JobExecution` concepts in Easy Batch. So some features will be more difficult to implement here.

I'm looking forward for your feedback.

Kind regards
Mahmoud

**Comment by benas** [comment] 2017-11-05 13:06
Hi @lauhin 

It took time but it is finally here 😄 

[Easy Jobs](https://github.com/j-easy/easy-jobs) comes with an administration interface that is able to run any kind of job (including easy batch jobs). I've added a sample Easy Batch job [here](https://gist.github.com/benas/68a8796afb451e91488c4b350cb7c865) and the corresponding config file for Easy Jobs.

The idea is to:

* Write a java class for the job
* Package the job in a shaded jar
* Add the jar in the `jobs` directory of the server distribution
* Request job execution through the REST api or the admin interface

The admin interface provides basic features for now, but some more interesting additions [are planned](https://github.com/j-easy/easy-jobs/issues).

If you have any suggestion, feedback or want to contribute, you are welcome!

Kind regards
Mahmoud

**Comment by veasmkii** [comment] 2017-11-05 14:08
That looks pretty beautiful!

**Comment by benas** [comment] 2017-11-05 14:26
Thank you @veasmkii !

**Comment by benas** [comment] 2017-11-05 18:54
I'm closing this issue.

Further discussions can be continued on Easy Jobs project.

**Closed by benas** 2017-11-05 18:54 UTC
Labels: feature
