### ISSUE TITLE
easy-batch-jdbc throws NPE if a value is null

### ISSUE THREAD

**Issue by seseso** [j-easy/easy-batch#375] opened 2020-06-26 21:09 UTC
If a value on a POJO record is null, the class BeanPropertiesPreparedStatementProvider throws an NPE:

```
java.lang.NullPointerException
	at org.jeasy.batch.jdbc.BeanPropertiesPreparedStatementProvider.prepareStatement(BeanPropertiesPreparedStatementProvider.java:113)
	at org.jeasy.batch.jdbc.JdbcRecordWriter.writeRecords(JdbcRecordWriter.java:80)
	at org.jeasy.batch.core.job.BatchJob.writeBatch(BatchJob.java:251)
	at org.jeasy.batch.core.job.BatchJob.call(BatchJob.java:112)
	at org.jeasy.batch.core.job.BatchJob.call(BatchJob.java:54)
```

I believe that it should check if the value is null and, otherwise, try to get the value type.

**Comment by benas** [comment] 2020-07-04 16:09
This is a duplicate of #372 .

**Closed by benas** 2020-07-04 16:09 UTC
