### ISSUE TITLE
JMX: Unexpected behaviour when new job instance uses already used name

### ISSUE THREAD

**Issue by tobias--** [j-easy/easy-batch#289] opened 2017-06-14 09:51 UTC
When creating a new job with the same name as a previously existing job, jmx notifications might go unnoticed because an MBean with the same name is already registered and new notifications start with the sequence number 1, which probably has already been used. In jconsole for example no values are being updated for the second job instance with the same name. I did not check whether this is the fault of jconsole or that the MBeanServer does not propagate sequence numbers it already saw in the past.

https://github.com/j-easy/easy-batch/blob/master/easybatch-core/src/main/java/org/easybatch/core/job/JobMonitor.java#L132-L145 

I am not quite sure how to handle this scenario appropriately.

When checking if the bean is already registered (in JobMonitor.java#L138), check also if it is the current instance that registered it. If a different instance registered several options come to mind:
- Fail in an appropriate way
- Unregister the bean and reregister with the current bean. This would be a bad solution, because identically named jobs may run in parallel. Also, you might lose information about a previously executed job.
- Register bean with name and append an appropriate sequence number

**Comment by benas** [comment] 2017-09-08 09:50
Hi @tobias-- 

Sorry for the late reply.

Given the test in JobMonitor.java#L138, I'm not sure how you ended up with two MBeans registered for two jobs having the same name.

Now that this issue is raised, I want to make sure that `mbs.isRegistered(name)` returns false when passing a different instance of `ObjectName` having the same name as a previously registered instance.

**Comment by benas** [comment] 2017-10-05 15:04
Hi,

> I want to make sure that mbs.isRegistered(name) returns false when passing a different instance of ObjectName having the same name as a previously registered instance.

The `isRegistered` method is behaving as expected. I used the following tests to confirm it:

```java
    @Test(expected = InstanceAlreadyExistsException.class)
    public void test1() throws Exception {
        MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
        ObjectName name1 = new ObjectName(JMX_MBEAN_NAME + "name=" + "myjob");
        ObjectName name2 = new ObjectName(JMX_MBEAN_NAME + "name=" + "myjob");
        mbs.registerMBean(new JobMonitor(null ), name1);
        // try to register another mbean with the same name (but a different ObjectName instance)
        mbs.registerMBean(new JobMonitor(null ), name2);
    }

    @Test
    public void test2() throws Exception {
        MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
        ObjectName name1 = new ObjectName(JMX_MBEAN_NAME + "name=" + "myjob");
        ObjectName name2 = new ObjectName(JMX_MBEAN_NAME + "name=" + "myjob");
        if (!mbs.isRegistered(name1)) {
            mbs.registerMBean(new JobMonitor(null ), name1);
        }
        if (!mbs.isRegistered(name2)) {
            fail("isRegistered should not return false for a different ObjectName instance having the same canonical name as a previously registered MBean ");
            mbs.registerMBean(new JobMonitor(null ), name2);
        }
        Set<ObjectName> objectNames = mbs.queryNames(new ObjectName(JMX_MBEAN_NAME + "*"), null);
        Assertions.assertThat(mbs.isRegistered(name1)).isTrue();
        Assertions.assertThat(mbs.isRegistered(name2)).isTrue();
        Assertions.assertThat(objectNames).hasSize(1);
        Assertions.assertThat(objectNames.iterator().next().getCanonicalName()).isEqualTo(JMX_MBEAN_NAME + "name=myjob");
    }
```

Both tests pass, so surprises regarding the expected behaviour of `isregistered`.

Now, I tried to reproduce your issue by submitting two jobs having the same name:

```java
Job job1 = JobBuilder.aNewJob().named("myjob").enableJmx(true).build();
Job job2 = JobBuilder.aNewJob().named("myjob").enableJmx(true).build();

JobExecutor jobExecutor = new JobExecutor();
jobExecutor.submitAll(job1, job2);
```

And I've introduced this small change to `JobMonitor` for logging purposes:

```diff
void registerJmxMBeanFor(Job job) {
    LOGGER.log(Level.INFO, "Registering JMX MBean for job {0}", job.getName());
    MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
    ObjectName name;
    try {
        name = new ObjectName(JMX_MBEAN_NAME + "name=" + job.getName());
        if (!mbs.isRegistered(name)) {
            mbs.registerMBean(this, name);
            LOGGER.log(Level.INFO, "JMX MBean registered successfully as: {0}", name.getCanonicalName());
+        } else {
+            LOGGER.log(Level.WARNING, String.format("Unable to register MBean for job %s, another job + having the same name is already registered", job.getName()));
+         }
    } catch (Exception e) {
        LOGGER.log(Level.WARNING, String.format("Unable to register MBean for job %s", job.getName()), e);
    }
}
```

When I execute this test, sometimes I get this:

```
2017-10-05 16:53:35.408 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' starting 
2017-10-05 16:53:35.422 INFO [org.easybatch.core.job.BatchJob start] - Batch size: 100 
2017-10-05 16:53:35.427 INFO [org.easybatch.core.job.BatchJob start] - Error threshold: N/A 
2017-10-05 16:53:35.428 INFO [org.easybatch.core.job.BatchJob start] - Jmx monitoring: true 
2017-10-05 16:53:35.430 INFO [org.easybatch.core.job.JobMonitor registerJmxMBeanFor] - Registering JMX MBean for job myjob 
2017-10-05 16:53:35.402 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' starting 
2017-10-05 16:53:35.433 INFO [org.easybatch.core.job.BatchJob start] - Batch size: 100 
2017-10-05 16:53:35.434 INFO [org.easybatch.core.job.BatchJob start] - Error threshold: N/A 
2017-10-05 16:53:35.438 INFO [org.easybatch.core.job.BatchJob start] - Jmx monitoring: true 
2017-10-05 16:53:35.438 INFO [org.easybatch.core.job.JobMonitor registerJmxMBeanFor] - Registering JMX MBean for job myjob 
2017-10-05 16:53:35.508 INFO [org.easybatch.core.job.JobMonitor registerJmxMBeanFor] - JMX MBean registered successfully as: org.easybatch.core.monitor:name=myjob 
2017-10-05 16:53:35.509 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' started 
2017-10-05 16:53:35.509 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' stopping 
2017-10-05 16:53:35.510 INFO [org.easybatch.core.job.BatchJob teardown] - Job 'myjob' finished with status: COMPLETED 
2017-10-05 16:53:35.511 WARNING [org.easybatch.core.job.JobMonitor registerJmxMBeanFor] - Unable to register MBean for job myjob, another job having the same name is already registered 
2017-10-05 16:53:35.511 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' started 
2017-10-05 16:53:35.512 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' stopping 
2017-10-05 16:53:35.513 INFO [org.easybatch.core.job.BatchJob teardown] - Job 'myjob' finished with status: COMPLETED 
```

and sometimes this:

```
2017-10-05 16:55:55.512 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' starting 
2017-10-05 16:55:55.520 INFO [org.easybatch.core.job.BatchJob start] - Batch size: 100 
2017-10-05 16:55:55.526 INFO [org.easybatch.core.job.BatchJob start] - Error threshold: N/A 
2017-10-05 16:55:55.528 INFO [org.easybatch.core.job.BatchJob start] - Jmx monitoring: true 
2017-10-05 16:55:55.528 INFO [org.easybatch.core.job.JobMonitor registerJmxMBeanFor] - Registering JMX MBean for job myjob 
2017-10-05 16:55:55.504 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' starting 
2017-10-05 16:55:55.530 INFO [org.easybatch.core.job.BatchJob start] - Batch size: 100 
2017-10-05 16:55:55.531 INFO [org.easybatch.core.job.BatchJob start] - Error threshold: N/A 
2017-10-05 16:55:55.532 INFO [org.easybatch.core.job.BatchJob start] - Jmx monitoring: true 
2017-10-05 16:55:55.532 INFO [org.easybatch.core.job.JobMonitor registerJmxMBeanFor] - Registering JMX MBean for job myjob 
2017-10-05 16:55:55.594 INFO [org.easybatch.core.job.JobMonitor registerJmxMBeanFor] - JMX MBean registered successfully as: org.easybatch.core.monitor:name=myjob 
2017-10-05 16:55:55.594 WARNING [org.easybatch.core.job.JobMonitor registerJmxMBeanFor] - Unable to register MBean for job myjob 
javax.management.InstanceAlreadyExistsException: org.easybatch.core.monitor:name=myjob
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.easybatch.core.job.JobMonitor.registerJmxMBeanFor(JobMonitor.java:139)
	at org.easybatch.core.job.BatchJob.registerJobMonitor(BatchJob.java:134)
	at org.easybatch.core.job.BatchJob.start(BatchJob.java:129)
	at org.easybatch.core.job.BatchJob.call(BatchJob.java:96)
	at org.easybatch.core.job.BatchJob.call(BatchJob.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-10-05 16:55:55.594 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' started 
2017-10-05 16:55:55.595 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' started 
2017-10-05 16:55:55.596 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' stopping 
2017-10-05 16:55:55.596 INFO [org.easybatch.core.job.BatchJob setStatus] - Job 'myjob' stopping 
2017-10-05 16:55:55.596 INFO [org.easybatch.core.job.BatchJob teardown] - Job 'myjob' finished with status: COMPLETED 
2017-10-05 16:55:55.596 INFO [org.easybatch.core.job.BatchJob teardown] - Job 'myjob' finished with status: COMPLETED 
```

I guess this is due to concurrency but it's not the point here. The point is that in both cases, there is no 'duplicate' MBeans for the same job name. So I'm not sure how you ended up with two MBeans registered for two jobs having the same name.

Sorry for the long comment, but I had to explain the steps of my investigation.
What do you think about this?

If I'm not wrong, you suggest to replace the warning I've added with one of theses possibilities:

* Fail in an appropriate way
* Unregister the bean and reregister with the current bean. This would be a bad solution, because identically named jobs may run in parallel. Also, you might lose information about a previously executed job.
* Register bean with name and append an appropriate sequence number

Is this correct?

Kr
Mahmoud

**Comment by benas** [comment] 2017-11-05 18:49
Have you got a chance to see my reply?

> When creating a new job with the same name as a previously existing job,

Even though I was not able to reproduce the issue (see my previous comment), this is not supposed to happen in the first place. I've added a note in the [documentation](https://github.com/j-easy/easy-batch/wiki/job-monitoring) about this:

"NB: You must ensure that JMX-enabled jobs have a unique name. Otherwise, notifications will be mixed or lost."

That said, I don't consider this as an Easy Batch issue anymore 😄 

What do you think?

**Comment by benas** [comment] 2017-11-08 10:29
Hi @tobias-- 

Since the expected behaviour is documented now, I think we can close this issue.
Please make sure to use a different name for your jobs when enabling JMX.

Best regards
Mahmoud

**Closed by benas** 2017-11-08 10:29 UTC
Labels: waiting for feedback
